### ISSUE TITLE
Server Crash -Cannot set property PropertyBool

### ISSUE THREAD

**Issue by ProsperCraft** [SgtPunishment/Soul-Shards-The-Old-Ways#55]
https://gist.github.com/ProsperCraft/2711e1e987ec56e10396ffa70da13ad1

java.lang.IllegalArgumentException: Cannot set property PropertyBool{name=active, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:210)
	at com.whammich.sstow.tile.TileEntityCage.setActiveState(TileEntityCage.java:159)
	at com.whammich.sstow.tile.TileEntityCage.func_73660_a(TileEntityCage.java:76)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:212)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:1321)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjl000(WorldServer.java:1308)
	at net.minecraft.world.World.func_72939_s(World.java:1282)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:717)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Not sure what players were doing, we have recently updated from InfinityLite 1.4.1 to 1.5.1

**Comment by TehNut** [comment]
Wrong tracker and this is a Sponge issue.

**Comment by rmnaderdev** [comment]
Nope it's not a sponge issue. I am getting it on Minecraft Version: 1.12.1 with forge-1.12.1-14.22.1.2484-universal. https://pastebin.com/BGUYSq0X

**Comment by TehNut** [comment]
It is also not my issue. And, yet again, wrong tracker.

**Comment by rmnaderdev** [comment]
Whoops! My bad.
